### ISSUE TITLE
arduino

### ISSUE THREAD

**Issue by skraburski** [dvernooy/ErgWare#1]
Hi Dave,
I absolutelt love your project, kudos for that!!!

I've spare arduino uno smd at home and was thinking on using it as it is using ATmega328 as you did in your project but I could spare time on designing hardware. I would just need to connect display, sensor and buttons and it would be ready. 

Did you ever think of that or maybe have ready version of your soft that I could put on arduino?

Regards
Lukasz

**Comment by dvernooy** [comment]
**Update:

Hi Lukasz ... I built a new version of the code (v0.4) for the Arduino Uno. You can find the code as well as a pdf instruction of how to get it installed on the Uno in the folder there. Here is a direct link to the instructions:

https://github.com/dvernooy/ErgWare/tree/master/v0.4/instructions

The only thing I haven't tested with it is the hardware chopper wheel .. the "CD" interrupter of the LED/photodiode. But I am sure it will work.  Note that I am using the Arduino Uno in a bit of a non-traditional way - to program my code I don't use the Arduino environment at all. 

Take a look, hopefully you can make some use of it.

-Dave**

----------------------------------
Hi Lukasz, there are a couple of options for Arduino compatibility.

Option 1 is to use your Arduino Uno hardware board, but not the Arduino bootloader. In this case, you would program the board directly from something like Atmel studio, or whatever environment you want that uses avr-gcc & avrdude. There are several tutorials on-line about how to do this. You might have to change the clock fuse settings & a few lines of code to map ports (for the buttons, sensor and display) depending on which of the '328 ports the Uno makes available. I have not looked into it, but I think I have an Uno lying around at home and can help with this if you are really serious about it. It also means you would have to re-install the bootloader if you ever wanted to re-use the Uno because Option 1 would over-write it. This may sound difficult, but I think it is actually really very simple.

Option 2 is to make an Arduino wrapper for the code. That could be quite a bit more involved given the use of the RTOS in the latest version. There are a couple of Arduino versions of the RTOS on-line that could be used, but I definitely have not studied them. My feeling is this method is (way) more involved that Option 1 ... but I understand it could be more satisfying to many people because it would use the Arduino environment they are used to. But again, if you are really serious about going down this route I'd be happy to help out. 

Let me know if this is still something you are thinking about.

-Dave
